

services:
  mongo:
    image: mongo:8.0
    container_name: formbuilder-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data-v8:/data/db

  backend:
    build: ./backend
    container_name: formbuilder-backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/formbuilder
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: formbuilder-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

volumes:
  mongo-data-v8:
